# Shell variables
# Generated by 'wal'
wallpaper='$DOTFILES/wallpaper/default.png'

# Special
background='#000000'
foreground='#f0d0a3'
cursor='#f0d0a3'

# Colors
color0='#000000'
color1='#72462C'
color2='#913513'
color3='#A25024'
color4='#D16A24'
color5='#C86E3D'
color6='#E88D34'
color7='#f0d0a3'
color8='#a89172'
color9='#72462C'
color10='#913513'
color11='#A25024'
color12='#D16A24'
color13='#C86E3D'
color14='#E88D34'
color15='#f0d0a3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
