# Shell variables
# Generated by 'wal'
wallpaper='/home/fede/dotfiles/wallpaper/default.png'

# Special
background='#120d0d'
foreground='#ddd1c0'
cursor='#ddd1c0'

# Colors
color0='#120d0d'
color1='#8F322B'
color2='#8A7462'
color3='#9B8872'
color4='#7E7F81'
color5='#8B8B8C'
color6='#B09F8B'
color7='#ddd1c0'
color8='#9a9286'
color9='#8F322B'
color10='#8A7462'
color11='#9B8872'
color12='#7E7F81'
color13='#8B8B8C'
color14='#B09F8B'
color15='#ddd1c0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
