# Shell variables
# Generated by 'wal'
wallpaper='/home/fede/dotfiles/wallpaper/default.png'

# Special
background='#0E1827'
foreground='#9ac4e0'
cursor='#9ac4e0'

# Colors
color0='#0E1827'
color1='#286496'
color2='#2867A5'
color3='#2961AB'
color4='#4C598B'
color5='#646B9A'
color6='#9477A2'
color7='#9ac4e0'
color8='#6b899c'
color9='#286496'
color10='#2867A5'
color11='#2961AB'
color12='#4C598B'
color13='#646B9A'
color14='#9477A2'
color15='#9ac4e0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
